apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-gateway-options
  namespace: istio-ingress
data:
  service: |
    spec:
      type: LoadBalancer
      loadBalancerIP: 192.168.4.60
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: istio-ingress
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: platform-gateway-options
  listeners:
    - name: http
      hostname: "*.steventidd.com"
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
