---
- name: Install common packages on Rocky Linux nodes
  hosts: rocky
  become: true
  tasks:
    - name: Ensure EPEL repo is installed
      dnf:
        name: epel-release
        state: present

    - name: Refresh DNF cache
      dnf:
        update_cache: true
        
    - name: Install htop
      dnf:
        name: htop
        state: present
